####
#### Make executable
####

## Root directory of project
PROJECT_ROOT := ..

## Source files
SRCS := $(wildcard *.cpp)

## Target executable
TRGT := a.out

## Run executable
RUN_COMMAND := ./$(TRGT)

-include ../config.mk
-include $(DEPS)
